# Generated by Django 5.1.3 on 2024-12-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
    ]
